### ISSUE TITLE
Make ETF Rifle projectiles faster

### ISSUE THREAD

**Issue by ceeeKay** [ceeeKay/Q2ETweaks#20]
It's as bad for multiplayer as the Q1 nailguns- let's offer a fix for that

**Comment by BathySalts** [comment]
Faster Projectiles Would Also Help Differentiate The Nailgun From The Hyperblaster, As It Stands Right Now They're Very Similar To Eachother

**Comment by ceeeKay** [comment]
available in v0.13 via `g_faster_flechettes` or more generally `g_faster_projectiles`
