### ISSUE TITLE
Feature Request: Custom Map Rotation

### ISSUE THREAD

**Issue by CarnageHeart** [ceeeKay/Q2ETweaks#21]
Is it possible to enable a custom map rotation, for example a maplist.txt file that will load those maps instead of the default map list option built in to the re-release. This way we can have custom maps in rotation or even the DM versions of the single player maps.

**Comment by ceeeKay** [comment]
Thanks for the suggestion! I think this feature is actually already available as `g_map_list` in the Q2 Remaster (unmodified).

The menus will only show what's in `mapdb.json` (the maps built in) but you can put a space-separated list of any map names in `g_map_list`.

You should be able to also put a list e.g. `g_map_list "base1 base2 base3"` into a file in your quake directory with a name such as mymaps.cfg and exec it from the console via `exec mymaps.cfg`.

I could potentially implement something additional here, but it feels like it'll be a bit redundant with something the game can already do without mods.

**Comment by CarnageHeart** [comment]
Ah, sorry I didn't realize that feature was already implemented. Thank you for the info :)
