### ISSUE TITLE
Feature Request: Auto-Hop

### ISSUE THREAD

**Issue by AgitationSkeleton** [ceeeKay/Q2ETweaks#23]
Simply put, enabling this convar would allow the player to hold +jump to repeatedly jump without requiring timing for pressing jump to gain momentum with bunnyhopping, just an easier method since Quake 2's bunnyhopping feels more stiff than QW's to me.

**Comment by ceeeKay** [comment]
Thanks for the suggestion! The Q2 remaster (and I presume vanilla Q2) behaves the same way as Q1/QW wherein you can press and hold jump at any time once you're in mid-air and upon landing you'll immediately jump again. If you haven't played around with `sv_speedometer 1` enabled it might be worth a try to see what kinds of speeds you can hit. I can pretty easily hit about 550+ in 3 strafe jumps on the bottom of the pit on q2dm1.

I can look into whether there's a way to ignore a held jump button, however, and whether this would be tough to add as an optional cvar.

**Comment by ceeeKay** [comment]
Easy enough. Included in v0.14 as `sv_auto_bhop`
