### ISSUE TITLE
Feature request: g_no_invulnerability

### ISSUE THREAD

**Issue by AgitationSkeleton** [ceeeKay/Q2ETweaks#26]
I'm not a fan of the invulnerability powerup for obvious reasons, and on maps such as 64dm1 Agony where it rotates with the Quad Damage I'd prefer if it were only the Quad Damage. This cvar would disable it in the rotation.

(Thank you very much for adding autohop, by the way!)

**Comment by ceeeKay** [comment]
Added along with some others in v0.16. Thanks for the suggestion!

```
g_no_powerups
g_no_quad
g_no_dualfire
g_no_invulnerability
g_no_invisibility
```
