### ISSUE TITLE
Gametime issue with match mode

### ISSUE THREAD

**Issue by deggieq2** [ceeeKay/Q2ETweaks#32]
Hi

Playing ctf and using the match mode your game time bugged out and started displaying negative numbers as the map had gone over the 20mins timelimit that was originally set.

Needs to update once the match starts with the new timer.

Thanks

**Comment by kevinworth** [comment]
Thanks! I haven't played around with match mode yet for TDM or CTF and I probably need to be checking/using a CTF match timer variable when in competition mode. The CTF HUD also has some amount of status/display, but again having not tried it much myself, I'm not sure what all it displays. Sounds like time for me to do some testing in this mode, including maybe teaching bots how to vote yes/ready (or be ignored when counting total players)

**Comment by ceeeKay** [comment]
Thanks! I haven't played around with match mode yet for TDM or CTF and I probably need to be checking/using a CTF match timer variable when in competition mode. The CTF HUD also has some amount of status/display, but again having not tried it much myself, I'm not sure what all it displays. Sounds like time for me to do some testing in this mode, including maybe teaching bots how to vote yes/ready (or be ignored when counting total players)

**Comment by ceeeKay** [comment]
![image](https://github.com/ceeeKay/Q2Eaks/assets/1403534/9fb217e3-dc44-493f-9416-c4e0efd578c5)

Yeah I think sv_game_timer just shouldn't be printed- match mode has its own timer which is better to rely on, I think, since it already has the logic to show warmup, match, etc

**Comment by ceeeKay** [comment]
The logic to force the two to be mutually exclusive isn't necessarily straightforward and is going to end up a bit hacky. I think I'd simply suggest setting `sv_match_timer 0` if you're going to run a server in match mode. If you're an admin you can also disable it from the Q2Eaks menu.

**Comment by deggieq2** [comment]
Yup good point - does seem pointless having both! Will do that next time

Thanks!
